# Generated by Django 5.1 on 2024-10-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2024', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default='Descripción no proporcionada'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='curso',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado')], default='curso', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project2024.usuario')),
                ('especialidad', models.CharField(max_length=255)),
                ('fecha_contratacion', models.DateField()),
                ('facultad', models.CharField(max_length=255)),
                ('escuela', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('jubilado', 'Jubilado')], default='activo', max_length=10)),
                ('codigo', models.CharField(choices=[('invitado', 'Invitado'), ('oficial', 'Oficial')], max_length=10)),
            ],
            bases=('project2024.usuario',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project2024.usuario')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('project2024.usuario',),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('pendiente', 'Pendiente')], max_length=10)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.curso')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('Paypal', 'Paypal'), ('manual', 'Manual')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('inscripcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.inscripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project2024.docente'),
        ),
    ]
