# Generated by Django 5.1 on 2024-10-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2024', '0002_usuario_curso_capacidad_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project2024.usuario')),
                ('departamento', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('acceso', models.CharField(choices=[('solo_ver', 'Solo Ver'), ('ver_agregar', 'Ver y Agregar'), ('superusuario', 'Superusuario')], default='solo_ver', max_length=15)),
            ],
            bases=('project2024.usuario',),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('ingresos', 'Ingresos'), ('pagos_pendientes', 'Pagos Pendientes'), ('asistencia', 'Asistencia')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='docente_id',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='curso_id',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='estudiante_id',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='inscripcion_id',
            new_name='inscripcion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='contraseña',
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('Paypal', 'Paypal'), ('manual', 'Manual')], max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('cedula', 'correo')},
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago_anterior', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], max_length=15)),
                ('estado_pago_nuevo', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], max_length=15)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('recordatorio_pago', 'Recordatorio de Pago'), ('ingreso_registrado', 'Ingreso Registrado')], max_length=25)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2024.usuario')),
            ],
        ),
    ]
