# Generated by Django 5.1 on 2024-10-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2024', '0003_administrativo_reporte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='docente',
            new_name='docente_id',
        ),
    ]
