# Generated by Django 5.0.7 on 2024-11-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2024', '0004_rename_docente_curso_docente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
